# Site settings
title: "yijing chen"
description: "Ph.D. candidate in Network Science"
baseurl: "/" # required if used under gh-pages branch, else (under master branch) just leave empty/blank
url: "https://yijingch.github.io"
author: "yijingch"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave empty to disable it
google_analytics:
disqus_shortname: 

plugins:
  - jekyll-sitemap

exclude: ["LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script"]
